//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GacExplorer.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GacExplorer.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly successfully registered in GAC.
        /// </summary>
        internal static string AssemblySuccessfullyRegisteredInGac {
            get {
                return ResourceManager.GetString("AssemblySuccessfullyRegisteredInGac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly successfully unregistered from GAC.
        /// </summary>
        internal static string AssemblySuccessfullyUnregisteredFromGac {
            get {
                return ResourceManager.GetString("AssemblySuccessfullyUnregisteredFromGac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly &apos;{0}&apos; will be removed from Global Assembly Cache. Continue?.
        /// </summary>
        internal static string AssemblyWillBeRemovedFromGlobalAssemblyCacheContinue {
            get {
                return ResourceManager.GetString("AssemblyWillBeRemovedFromGlobalAssemblyCacheContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when registering assembly in GAC.
        /// </summary>
        internal static string ErrorWhenRegisteringAssemblyInGac {
            get {
                return ResourceManager.GetString("ErrorWhenRegisteringAssemblyInGac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during saving GacUtil.exe location.
        /// </summary>
        internal static string ErrorWhenSavingGacUtilLocation {
            get {
                return ResourceManager.GetString("ErrorWhenSavingGacUtilLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when unregistering assembly from GAC.
        /// </summary>
        internal static string ErrorWhenUnregisteringAssemblyFromGac {
            get {
                return ResourceManager.GetString("ErrorWhenUnregisteringAssemblyFromGac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm uninstalling.
        /// </summary>
        internal static string PleaseConfirmUninstalling {
            get {
                return ResourceManager.GetString("PleaseConfirmUninstalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select single assembly to be uninstalled from GAC.
        /// </summary>
        internal static string SelectSingleAssemblyToBeUninstalledFromGac {
            get {
                return ResourceManager.GetString("SelectSingleAssemblyToBeUninstalledFromGac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to configure localization of GacUtil.exe tool before performing registration.
        /// </summary>
        internal static string YouNeedToConfigureLocalizationOfGacUtilToolBeforePerformingRegistration {
            get {
                return ResourceManager.GetString("YouNeedToConfigureLocalizationOfGacUtilToolBeforePerformingRegistration", resourceCulture);
            }
        }
    }
}
